os: windows
language: node_js
node_js:  
  - "node"
install:
  - .\build\install_deps.ps1
jobs:
  include:
    - stage: build
      script: .\build\build_web.ps1
    - stage: test
      script: .\build\test_web.ps1