os: windows
language: node_js
node_js:  
  - "node"
install:
  - PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine'
  - PowerShell -Command '.\init.ps1;Install-Dependencies'
jobs:
  include:
    - stage: build
      script: PowerShell -Command '.\init.ps1;Build-Web'
    - stage: test
      script: PowerShell -Command '.\init.ps1;Test-Web'