os: windows
language: node_js
node_js:  
  - "node"
install:
  - PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine'
  - PowerShell -File init.ps1
jobs:
  include:
    - stage: build
      script: Build-Web
    - stage: test
      script: Test-Web